In [50]:
#Author: ML Tlachac, WPI
#For StudentSADD, 2021

import pandas as pd

data = pd.read_csv("unscriptedTranscript.csv")
print(data.shape)
data.head()

(110, 9)

,Unnamed: 0,id,phq9,q9,db_type,text,label,label_q9,id2
0,0,8181,3,0,summer1,a good friend is someone that is there for you...,0,0,1
1,1,8170,4,0,summer1,a good friend is someone that's always there f...,0,0,2
2,3,4041,12,0,summer1,a good friend is someone who is honest they ar...,1,0,4
3,10,8650,13,0,summer2,a good friend is someone who understands your ...,1,0,11
4,11,4782,16,0,summer2,a good friend in someone who's there for you w...,1,0,12

In [51]:
pDFt = pd.DataFrame()
pDFt["ID"] = data["id"]
pDFt["phq9"] = data["phq9"]
pDFt["q9"] = data["q9"]
pDFt["Content"] = data.text
pDFt.head()

     ID  phq9  q9                                            Content
0  8181     3   0  a good friend is someone that is there for you...
1  8170     4   0  a good friend is someone that's always there f...
2  4041    12   0  a good friend is someone who is honest they ar...
3  8650    13   0  a good friend is someone who understands your ...
4  4782    16   0  a good friend in someone who's there for you w...

In [52]:
#calculate length
characters = []
words = []
for i in range(0, pDFt.shape[0]):
    pDFt.Content[i][1:-1]
    characters.append(len(pDFt.Content[i][1:-1]))
    words.append(len(pDFt.Content[i][1:-1].split(" ")))
        
pDFt["Characters"] = characters
pDFt["Words"] = words

In [53]:
pDFt.head()

,ID,phq9,q9,Content,Characters,Words
0,8181,3,0,a good friend is someone that is there for you...,312,62
1,8170,4,0,a good friend is someone that's always there f...,140,29
2,4041,12,0,a good friend is someone who is honest they ar...,204,40
3,8650,13,0,a good friend is someone who understands your ...,396,77
4,4782,16,0,a good friend in someone who's there for you w...,174,36

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from textblob import TextBlob
import textblob as tb
import json
import nltk

In [55]:
#extract polarity, subjectivity, and part of speech tags for each word, stored as list for now
tags = []
for i in range(0, len(pDFt.ID)):
    print(i)
    tags2 = []
    for text in pDFt.Content[i]:
        T = TextBlob(str(text))
        for word, tag in T.tags:
            tags2.append(tag)
    tags.append(tags2)
pDFt["POStags"] = tags

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109

In [56]:
from empath import Empath
import re

#create list of all empath categories

lexicon = Empath()
emp = lexicon.analyze("Testing", normalize=True)
wordlist = []
for word, value in emp.items():
    wordlist.append(word)
print(wordlist)

['help', 'office', 'dance', 'money', 'wedding', 'domestic_work', 'sleep', 'medical_emergency', 'cold', 'hate', 'cheerfulness', 'aggression', 'occupation', 'envy', 'anticipation', 'family', 'vacation', 'crime', 'attractive', 'masculine', 'prison', 'health', 'pride', 'dispute', 'nervousness', 'government', 'weakness', 'horror', 'swearing_terms', 'leisure', 'suffering', 'royalty', 'wealthy', 'tourism', 'furniture', 'school', 'magic', 'beach', 'journalism', 'morning', 'banking', 'social_media', 'exercise', 'night', 'kill', 'blue_collar_job', 'art', 'ridicule', 'play', 'computer', 'college', 'optimism', 'stealing', 'real_estate', 'home', 'divine', 'sexual', 'fear', 'irritability', 'superhero', 'business', 'driving', 'pet', 'childish', 'cooking', 'exasperation', 'religion', 'hipster', 'internet', 'surprise', 'reading', 'worship', 'leader', 'independence', 'movement', 'body', 'noise', 'eating', 'medieval', 'zest', 'confusion', 'water', 'sports', 'death', 'healing', 'legend', 'heroic', 'celebration', 'restaurant', 'violence', 'programming', 'dominant_heirarchical', 'military', 'neglect', 'swimming', 'exotic', 'love', 'hiking', 'communication', 'hearing', 'order', 'sympathy', 'hygiene', 'weather', 'anonymity', 'trust', 'ancient', 'deception', 'fabric', 'air_travel', 'fight', 'dominant_personality', 'music', 'vehicle', 'politeness', 'toy', 'farming', 'meeting', 'war', 'speaking', 'listen', 'urban', 'shopping', 'disgust', 'fire', 'tool', 'phone', 'gain', 'sound', 'injury', 'sailing', 'rage', 'science', 'work', 'appearance', 'valuable', 'warmth', 'youth', 'sadness', 'fun', 'emotional', 'joy', 'affection', 'traveling', 'fashion', 'ugliness', 'lust', 'shame', 'torment', 'economics', 'anger', 'politics', 'ship', 'clothing', 'car', 'strength', 'technology', 'breaking', 'shape_and_size', 'power', 'white_collar_job', 'animal', 'party', 'terrorism', 'smell', 'disappointment', 'poor', 'plant', 'pain', 'beauty', 'timidity', 'philosophy', 'negotiate', 'negative_emotion', 'cleaning', 'messaging', 'competing', 'law', 'friends', 'payment', 'achievement', 'alcohol', 'liquid', 'feminine', 'weapon', 'children', 'monster', 'ocean', 'giving', 'contentment', 'writing', 'rural', 'positive_emotion', 'musical', 'colors', 'text_abbreviations']

In [57]:
#calculate frequency for each empath category
for word in wordlist:
    print(word)
    pctt = []
    for i in range(0, pDFt.shape[0]):
        content = re.sub(r'[^\w\s]', '', str(pDFt.Content[i]).lower())
        lexicon = Empath()
        emp = lexicon.analyze(content, categories=[word], normalize = True)
        if emp != None:
            for key, value in emp.items():
                pctt.append(value)
        else:
            pctt.append(0)
    pDFt[word] = pctt

help
office
dance
money
wedding
domestic_work
sleep
medical_emergency
cold
hate
cheerfulness
aggression
occupation
envy
anticipation
family
vacation
crime
attractive
masculine
prison
health
pride
dispute
nervousness
government
weakness
horror
swearing_terms
leisure
suffering
royalty
wealthy
tourism
furniture
school
magic
beach
journalism
morning
banking
social_media
exercise
night
kill
blue_collar_job
art
ridicule
play
computer
college
optimism
stealing
real_estate
home
divine
sexual
fear
irritability
superhero
business
driving
pet
childish
cooking
exasperation
religion
hipster
internet
surprise
reading
worship
leader
independence
movement
body
noise
eating
medieval
zest
confusion
water
sports
death
healing
legend
heroic
celebration
restaurant
violence
programming
dominant_heirarchical
military
neglect
swimming
exotic
love
hiking
communication
hearing
order
sympathy
hygiene
weather
anonymity
trust
ancient
deception
fabric
air_travel
fight
dominant_personality
music
vehicle
politeness
toy
farming
meeting
war
speaking
listen
urban
shopping
disgust
fire
tool
phone
gain
sound
injury
sailing
rage
science
work
appearance
valuable
warmth
youth
sadness
fun
emotional
joy
affection
traveling
fashion
ugliness
lust
shame
torment
economics
anger
politics
ship
clothing
car
strength
technology
breaking
shape_and_size
power
white_collar_job
animal
party
terrorism
smell
disappointment
poor
plant
pain
beauty
timidity
philosophy
negotiate
negative_emotion
cleaning
messaging
competing
law
friends
payment
achievement
alcohol
liquid
feminine
weapon
children
monster
ocean
giving
contentment
writing
rural
positive_emotion
musical
colors
text_abbreviations

In [59]:
#get list of Part of Speech (POS) tags
posTags = []
for i in range(0, pDFt.shape[0]):
    for tag in pDFt.POStags[i]:
        posTags.append(tag)
posSet = set(posTags)
print(posSet)

#POS tag counting
poswordst = []
for posList in pDFt.POStags:
    poswordst.append(len(posList))
pDFt["WordsTags"] = poswordst

for tag in posSet:
    cnt = []
    for posList in pDFt.POStags:
        counter = 0
        for item in posList:
            if item == tag:
                counter += 1
        cnt.append(counter)
    pDFt[tag] = cnt
    
#turn tag count into frequencies
for tag in posSet:
    freq = []
    for i in range(0, pDFt.shape[0]):
        freq.append(pDFt[tag][i]/poswordst[i])
    pDFt[tag] = freq

{'NNP', 'CD', 'NNS', 'PRP', 'DT', 'SYM', 'NN'}

In [60]:
pDFt.to_csv("aPromptTextFeatures.csv")